#!/bin/bash
current_dir=$(pwd)
mail_fail=$(readlink -f "${1}")
filename=$(basename "${mail_fail}")
file_dir=$(dirname "${mail_fail}")
docker run -it --rm --user=`id -u` --net=none -v "${current_dir}:/home/nonroot/" -v "${file_dir}:/data:ro" tabledevil/file-analysis munpack -t "/data/${filename}"
