#!/bin/bash
touchpad_id=$(xinput list | grep -i touch | grep -Po '(?<=id=)\d+')
if (xinput list-props ${touchpad_id} | grep "Device Enabled" | grep -Po '\d$' | grep -q "1"); then
  xinput disable "${touchpad_id}"
else
  xinput enable "${touchpad_id}"
fi
