version: '2.2'
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
        container_name: elasticsearch
        hostname: elasticsearch
        restart: unless-stopped
        ports:
        - "10.1.0.10:9200:9200"
        - "10.1.0.10:9300:9300"
        volumes:
        - elastic-data:/usr/share/elasticsearch/data
        environment:
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
        ulimits:
            memlock:
                soft: -1
                hard: -1

        networks:
        - elk

    kibana:
        image:
            kibana
        hostname: kibana
        restart: unless-stopped
        ports:
        - "10.1.0.10:5601:5601"
        networks:
        - elk
        depends_on:
        - elasticsearch

networks:
    elk:
        driver: bridge

volumes:
    elastic-data:
        driver: local
