version: '2'
services:
    elasticsearch:
        image:
            elasticsearch
        container_name: elasticsearch
        hostname: elasticsearch
        ports:
        - "9200:9200"
        - "9300:9300"
        volumes:
        - elastic-data:/usr/share/elasticsearch/data
        environment:
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
        ulimits:
            memlock:
                soft: -1
                hard: -1

        networks:
        - elk

    kibana:
        image:
            kibana
        hostname: kibana
        ports:
        - "5601:5601"
        networks:
        - elk
        depends_on:
        - elasticsearch

networks:
    elk:
        driver: bridge

volumes:
    elastic-data:
        driver: local
