version: '2'
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
        # container_name: elasticsearch
        hostname: elasticsearch
        ports:
        - "9200:9200"
        - "9300:9300"
        volumes:
        - elastic-data:/usr/share/elasticsearch/data
        environment:
        - node.name=elasticsearch
        - discovery.type=single-node
        # - discovery.seed_hosts=elasticsearch
        # - cluster.initial_master_nodes=es01,es02
        # - cluster.name=docker-cluster
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
        ulimits:
            memlock:
                soft: -1
                hard: -1

        networks:
        - elk

    kibana:
        image:
            docker.elastic.co/kibana/kibana:7.0.1
        # container_name: kibana
        hostname: kibana
        ports:
        - "5601:5601"
        networks:
        - elk
        depends_on:
        - elasticsearch

networks:
    elk:
        driver: bridge

volumes:
    elastic-data:
        driver: local
